# -*- coding: utf-8 -*-
"""30906030100615_project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTosfJi4wLisEuEyGbyQ8nkIHRXKV5sz
"""

import sqlite3
import pandas as pd
import json
from bs4 import BeautifulSoup

# File locations
database_file = "input_data/databases"
catalogue_file = "input_data/catalogue"
kickoff_file = "input_data/kickoff"

print("Files configured.")

# Connect to the SQLite database
conn = sqlite3.connect(database_file)

# Show the tables in the database
tables = pd.read_sql_query("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
""", conn)

print("tables ", tables)

q1 = pd.read_sql_query("""
    SELECT
        m.member_id,
        m.first_name,
        m.last_name,
        COUNT(c.checkout_id) AS checkout_count
    FROM members AS m
    LEFT JOIN checkouts AS c
        ON m.member_id = c.member_id
    GROUP BY
        m.member_id,
        m.first_name,
        m.last_name
    ORDER BY
        m.member_id;
""", conn)

print("q1 :")
q1

print("Number of members is:", len(q1))

print("Members with zero checkouts:", (q1["checkout_count"] == 0).sum())

"""Which books match a chosen author pattern?

Author pattern chosen: `D%`
"""

q2 = pd.read_sql_query("""
    SELECT
        book_id,
        title,
        author
    FROM books
    WHERE author LIKE 'D%'
    ORDER BY author, title;
""", conn)

q2

print("Books matching the pattern:", len(q2))

"""Whatare the most popular books?

highest checkouts, ranked from most borrowed to least borrowed.
"""

q3 = pd.read_sql_query("""
    SELECT
        b.book_id,
        b.title,
        b.author,
        COUNT(c.checkout_id) AS checkout_count
    FROM books AS b
    LEFT JOIN checkouts AS c
        ON b.book_id = c.book_id
    GROUP BY
        b.book_id,
        b.title,
        b.author
    ORDER BY
        checkout_count DESC,
        b.title ASC
    LIMIT 5;
""", conn)

q3

"""Who are the most active readers?

The ten members with the highest number of checkouts, ranked from most active to least active
"""

q4 = pd.read_sql_query("""
    SELECT
        m.member_id,
        m.first_name,
        m.last_name,
        COUNT(c.checkout_id) AS checkout_count
    FROM members AS m
    LEFT JOIN checkouts AS c
        ON m.member_id = c.member_id
    GROUP BY
        m.member_id,
        m.first_name,
        m.last_name
    ORDER BY
        checkout_count DESC,
        m.member_id ASC
    LIMIT 10;
""", conn)

q4

"""What does a neighborhood's activity look like further back in time?

Neighborhood selected: `Maadi`

The checkout records are ordered from newest to oldest, with the 10 most recent checkouts skipped.
"""

q5 = pd.read_sql_query("""
    SELECT
        c.checkout_id,
        c.member_id,
        m.first_name,
        m.last_name,
        m.neighborhood,
        c.book_id,
        b.title,
        c.checkout_date,
        c.return_date
    FROM checkouts AS c
    JOIN members AS m
        ON c.member_id = m.member_id
    JOIN books AS b
        ON c.book_id = b.book_id
    WHERE m.neighborhood = 'Maadi'
    ORDER BY c.checkout_date DESC
    LIMIT -1 OFFSET 10;
""", conn)

q5

# Load the book catalogue JSON
with open(catalogue_file, "r", encoding="utf-8") as f:
    catalogue_data = json.load(f)

catalogue = pd.DataFrame(catalogue_data)

print("Catalogue rows:", len(catalogue))
catalogue.head((32))

kickoff_tables = pd.read_html(kickoff_file)

print("Number of tables found:", len(kickoff_tables))

kickoff = kickoff_tables[0]

kickoff.head(10)

kickoff = kickoff.rename(columns={
    "Member ID": "member_id",
    "Book ID": "book_id",
    "Checkout Date": "checkout_date"
})

kickoff

kickoff["source"] = "Reading Kickoff"

kickoff.head()

database_checkouts = pd.read_sql_query("""
    SELECT
        checkout_id,
        member_id,
        book_id,
        checkout_date,
        return_date
    FROM checkouts
""", conn)

database_checkouts["source"] = "Database"

print("Database checkout records:", len(database_checkouts))

database_checkouts.head()

kickoff["checkout_id"] = pd.NA
kickoff["return_date"] = pd.NA

kickoff = kickoff[
    [
        "checkout_id",
        "member_id",
        "book_id",
        "checkout_date",
        "return_date",
        "source"
    ]
]

kickoff.head()

all_checkouts = pd.concat(
    [database_checkouts, kickoff],
    ignore_index=True
)

print("Database checkouts:", len(database_checkouts))
print("Reading Kickoff checkouts:", len(kickoff))
print("Combined checkouts:", len(all_checkouts))

all_checkouts.head(10)

members = pd.read_sql_query("""
    SELECT
        member_id,
        first_name,
        last_name,
        grade,
        neighborhood,
        membership_status,
        join_date
    FROM members
""", conn)

members.head(10)

all_checkouts = all_checkouts.merge(
    members,
    on="member_id",
    how="left"
)

all_checkouts.head(10)

books = pd.read_sql_query("""
    SELECT
        book_id,
        title,
        author
    FROM books
""", conn)

books.head()

all_checkouts = all_checkouts.merge(
    books,
    on="book_id",
    how="left"
)

all_checkouts.head(10)

all_checkouts = all_checkouts.merge(
    catalogue,
    on="book_id",
    how="left"
)

all_checkouts.head(16)

"""Task 1 : unified dataset and asking dataset questions"""

