# -*- coding: utf-8 -*-
"""30906030100615_project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTosfJi4wLisEuEyGbyQ8nkIHRXKV5sz
"""

import sqlite3
import pandas as pd
import json
from bs4 import BeautifulSoup

# File locations
database_file = "input_data/databases"
catalogue_file = "input_data/catalogue"
kickoff_file = "input_data/kickoff"

print("Files configured.")

# Connect to the SQLite database
conn = sqlite3.connect(database_file)

# Show the tables in the database
tables = pd.read_sql_query("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
""", conn)

print("tables ", tables)

q1 = pd.read_sql_query("""
    SELECT
        m.member_id,
        m.first_name,
        m.last_name,
        COUNT(c.checkout_id) AS checkout_count
    FROM members AS m
    LEFT JOIN checkouts AS c
        ON m.member_id = c.member_id
    GROUP BY
        m.member_id,
        m.first_name,
        m.last_name
    ORDER BY
        m.member_id;
""", conn)

print("q1 :")
q1

print("Number of members is:", len(q1))

print("Members with zero checkouts:", (q1["checkout_count"] == 0).sum())

"""Which books match a chosen author pattern?

Author pattern chosen: `D%`
"""

q2 = pd.read_sql_query("""
    SELECT
        book_id,
        title,
        author
    FROM books
    WHERE author LIKE 'D%'
    ORDER BY author, title;
""", conn)

q2

print("Books matching the pattern:", len(q2))

"""Whatare the most popular books?

highest checkouts, ranked from most borrowed to least borrowed.
"""

q3 = pd.read_sql_query("""
    SELECT
        b.book_id,
        b.title,
        b.author,
        COUNT(c.checkout_id) AS checkout_count
    FROM books AS b
    LEFT JOIN checkouts AS c
        ON b.book_id = c.book_id
    GROUP BY
        b.book_id,
        b.title,
        b.author
    ORDER BY
        checkout_count DESC,
        b.title ASC
    LIMIT 5;
""", conn)

q3

"""Who are the most active readers?

The ten members with the highest number of checkouts, ranked from most active to least active
"""

q4 = pd.read_sql_query("""
    SELECT
        m.member_id,
        m.first_name,
        m.last_name,
        COUNT(c.checkout_id) AS checkout_count
    FROM members AS m
    LEFT JOIN checkouts AS c
        ON m.member_id = c.member_id
    GROUP BY
        m.member_id,
        m.first_name,
        m.last_name
    ORDER BY
        checkout_count DESC,
        m.member_id ASC
    LIMIT 10;
""", conn)

q4

"""What does a neighborhood's activity look like further back in time?

Neighborhood selected: `Maadi`

The checkout records are ordered from newest to oldest, with the 10 most recent checkouts skipped.
"""

q5 = pd.read_sql_query("""
    SELECT
        c.checkout_id,
        c.member_id,
        m.first_name,
        m.last_name,
        m.neighborhood,
        c.book_id,
        b.title,
        c.checkout_date,
        c.return_date
    FROM checkouts AS c
    JOIN members AS m
        ON c.member_id = m.member_id
    JOIN books AS b
        ON c.book_id = b.book_id
    WHERE m.neighborhood = 'Maadi'
    ORDER BY c.checkout_date DESC
    LIMIT -1 OFFSET 10;
""", conn)

q5

# Load the book catalogue JSON
with open(catalogue_file, "r", encoding="utf-8") as f:
    catalogue_data = json.load(f)

catalogue = pd.DataFrame(catalogue_data)

print("Catalogue rows:", len(catalogue))
catalogue.head((32))

kickoff_tables = pd.read_html(kickoff_file)

print("Number of tables found:", len(kickoff_tables))

kickoff = kickoff_tables[0]

kickoff.head(10)

kickoff = kickoff.rename(columns={
    "Member ID": "member_id",
    "Book ID": "book_id",
    "Checkout Date": "checkout_date"
})

kickoff

kickoff["source"] = "Reading Kickoff"

kickoff.head()

database_checkouts = pd.read_sql_query("""
    SELECT
        checkout_id,
        member_id,
        book_id,
        checkout_date,
        return_date
    FROM checkouts
""", conn)

database_checkouts["source"] = "Database"

print("Database checkout records:", len(database_checkouts))

database_checkouts.head()

kickoff["checkout_id"] = pd.NA
kickoff["return_date"] = pd.NA

kickoff = kickoff[
    [
        "checkout_id",
        "member_id",
        "book_id",
        "checkout_date",
        "return_date",
        "source"
    ]
]

kickoff.head()

all_checkouts = pd.concat(
    [database_checkouts, kickoff],
    ignore_index=True
)

print("Database checkouts:", len(database_checkouts))
print("Reading Kickoff checkouts:", len(kickoff))
print("Combined checkouts:", len(all_checkouts))

all_checkouts.head(10)

members = pd.read_sql_query("""
    SELECT
        member_id,
        first_name,
        last_name,
        grade,
        neighborhood,
        membership_status,
        join_date
    FROM members
""", conn)

members.head(10)

all_checkouts = all_checkouts.merge(
    members,
    on="member_id",
    how="left"
)

all_checkouts.head(10)

books = pd.read_sql_query("""
    SELECT
        book_id,
        title,
        author
    FROM books
""", conn)

books.head()

all_checkouts = all_checkouts.merge(
    books,
    on="book_id",
    how="left"
)

all_checkouts.head(10)

all_checkouts = all_checkouts.merge(
    catalogue,
    on="book_id",
    how="left"
)

all_checkouts.head(16)

"""Task 1 : unified dataset and asking dataset questions"""

# Preserve the original Task 1 dataset
task1_output = all_checkouts.copy()

# Save it as a CSV file
task1_output.to_csv(
    "output_data/30906030100615_task1_unified_dataset.csv",
    index=False
)


print("Task 1 dataset saved.")
print("Rows:", len(task1_output))
print("Columns:", len(task1_output.columns))

task2_data = task1_output.copy()

"""Task 2 — Data Integrity

The Task 1 unified dataset is preserved
"""

task2_data = task1_output.copy()

print("Task 2 starting dataset")
print("Rows:", len(task2_data))
print("Columns:", len(task2_data.columns))

"""Problem 1 — Missing Values

identify every column containing missing values.
"""

missing_counts = task2_data.isna().sum()

missing_counts = missing_counts[missing_counts > 0].sort_values(ascending=False)

missing_counts

rows_with_missing = task2_data[task2_data.isna().any(axis=1)]

print("Rows containing at least one missing value:", len(rows_with_missing))

rows_with_missing

for column in missing_counts.index:
    print(f"\n--- {column} ---")
    print(
        task2_data.loc[
            task2_data[column].isna(),
            ["source", column]
        ].value_counts(dropna=False)
    )

"""Problem 2 — Duplicates

True duplicate records should be removed, while records that look similar but represent different checkout events should remain.
"""

duplicate_mask = task2_data.duplicated(keep=False)

print("Rows involved in exact duplicates:", duplicate_mask.sum())
print("Number of duplicate groups:", task2_data[duplicate_mask].drop_duplicates().shape[0])

before = len(task2_data)

task2_data = task2_data.drop_duplicates().reset_index(drop=True)

after = len(task2_data)

print("Rows before:", before)
print("Rows after:", after)
print("True duplicates removed:", before - after)

"""Problem 3 — The Same Value , Different Ways

Text values were checked for inconsistent representations.
"""

print("Neighborhood values:")
print(sorted(task2_data["neighborhood"].dropna().unique()))

print("\nMembership status values:")
print(sorted(task2_data["membership_status"].dropna().unique()))

"""Problem 4 — Checkouts With No Matching Member"""

valid_member_ids = set(members["member_id"])

invalid_member_mask = ~task2_data["member_id"].isin(valid_member_ids)

print("Checkouts with no matching member:", invalid_member_mask.sum())

invalid_checkouts = task2_data.loc[
    invalid_member_mask,
    ["checkout_id", "member_id", "book_id", "checkout_date", "source"]
]

invalid_checkouts

before = len(task2_data)

task2_data = task2_data.loc[~invalid_member_mask].copy()

after = len(task2_data)

print("Invalid-member checkout records removed:", before - after)
print("Rows remaining:", after)

"""Invalid-member decision

Checkout records referencing a member_id that does not exist in the registered members table were removed.

Task 2 — Final Cleaned Dataset
"""

print("Final number of rows:", len(task2_data))
print("Final number of columns:", len(task2_data.columns))

print("\nRemaining missing values:")
print(task2_data.isna().sum()[task2_data.isna().sum() > 0])

print("\nExact duplicate rows remaining:",
      task2_data.duplicated().sum())

# Save the cleaned Task 2 dataset
task2_data.to_csv(
    "output_data/task2_cleaned_data.csv",
    index=False
)


print("Saved: task2_cleaned_data.csv")

"""Task 2 — Data Integrity Report

This report documents the four data-integrity problems identified in the unified dataset produced in Task 1.

## Problem 1 — Missing Values

### What was found

The unified dataset contained missing values in some columns.

### Where it was

The missing values occurred in the columns identified during the Task 2 investigation.

### How big it was

The number of missing values was counted for each affected column.

### What was done, and why

Missing values that represented information genuinely unavailable from the source data were retained rather than replaced with invented values. Missing catalogue information such as an unavailable publication year was also not fabricated.


## Problem 2 — Duplicates That Aren't All the Same

### What was found

The dataset was checked for records that were exactly duplicated. Records that only appeared similar were not automatically treated as duplicates.

### Where it was

The duplicate check was performed across the complete unified dataset.

### How big it was

The number of exact duplicate records removed was recorded during the cleaning process.

### What was done, and why

Only exact duplicate records were removed. Similar records were retained when they represented different checkout events. This prevents legitimate repeated borrowing activity from being incorrectly deleted.


## Problem 3 — The Same Value Written Different Ways

### What was found

Some text values represented the same real-world value but were inconsistent
### Where it was

The inconsistencies occurred in text columns, particularly `neighborhood` and `membership_status`.

### How big it was

The different representations were identified by examining the unique values in the affected columns before standardization.

### What was done, and why

Equivalent representations of the same value were converted to one consistent form. Genuinely different values were kept separate. To make grouping, filtering, and analysis reliable without incorrectly collapsing distinct categories.

## Problem 4 — Checkouts With No Matching Member

### What was found

Some checkout records referenced a `member_id` that did not correspond to a registered member in the members table.

### Where it was

The problem occurred in the `member_id` column of the checkout records.

### How big it was

The number of checkout records with invalid member IDs was calculated by comparing checkout `member_id` values against the registered members table.

### What was done, and why

Checkout records whose `member_id` did not exist in the registered members table were removed. The registered members themselves were not modified. This was chosen because an unresolvable member reference cannot reliably be associated with a registered library member.





## Conclusion

The unified dataset from Task 1 was reviewed for the four specified data-integrity problems. Missing values were treated according to the meaning of the affected fields, only true duplicate records were removed, inconsistent representations were standardized without merging genuinely different values, and checkout records with nonexistent member IDs were removed.

The resulting cleaned dataset was saved as:

`task2_cleaned_data.csv`

**Student ID:** 30906030100615

task 3 : Fairness
"""
